### PR TITLE
Fix #6

### LINKED ISSUE #6: [Android] Accessing TemporaryImagePath throws a UnityException: get_temporaryCachePath can only be called from the main thread.
**Description of the bug**

Using `LoadImageAsync()` without having first loaded an image synchronously results in the lazy evaluation of `TemporaryImagePath` to happen on a worker thread. 
In turn, the getter accesses `Application.temporaryCachePath` on the same worker thread, and Unity complains.

**Reproduction steps**

Use `TextureOps.LoadImageAsync()` without first using any function that initializes `TemporaryImagePath`.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.18
- Platform: Android (Windows editor)
- How did you download the plugin: OpenUPM

**Additional info**
```
2023/03/22 10:58:50.191 2747 4856 Error Unity UnityException: get_temporaryCachePath can only be called from the main thread.
2023/03/22 10:58:50.191 2747 4856 Error Unity Constructors and field initializers will be executed from the loading thread when loading a scene.
2023/03/22 10:58:50.191 2747 4856 Error Unity Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
2023/03/22 10:58:50.191 2747 4856 Error Unity   at (wrapper managed-to-native) UnityEngine.Application.get_temporaryCachePath()
2023/03/22 10:58:50.191 2747 4856 Error Unity   at TextureOps.get_TemporaryImagePath () [0x0000e] in C:\Dev\Frontend\AesticoVisualizerFuture\Library\PackageCache\com.yasirkula.textureops@1.2.1\Plugins\TextureOps\TextureOps.cs:114 
2023/03/22 10:58:50.191 2747 4856 Error Unity   at TextureOps+<>c__DisplayClass18_0.<LoadImageAsync>b__0 () [0x0001f] in C:\Dev\Frontend\AesticoVisualizerFuture\Library\PackageCache\com.yasirkula.textureops@1.2.1\Plugins\TextureOps\TextureOps.cs:278 
2023/03/22 10:58:50.191 2747 4856 Error Unity   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <e542e16f149446db91d697a00bb38b65>:0 
2023/03/22 10:58:50.191 2747 4856 Error Unity   at System.Threading.Tasks.Task.Execute () [0x00000] in <e542e16f149446db91d697a00bb38b65>:0 
2023/03/22 10:58:50.191 2747 4856 Error Unity --- End of stack trace from previous
```

### PR DESCRIPTION
**Pull request by Girildo**

### CODE REVIEW

**Comment by Girildo** [comment]
This is not tested yet.

**Comment by Girildo** [comment]
Tested on Android

**Comment by yasirkula** [comment]
It makes sense that my code would fail but what's surprising is, it didn't fail in my tests while I was writing this function. I must've been calling TemporaryImagePath via another function prior to async functions then. Can you apply the same solution to GetVideoThumbnailAsync?

**Comment by Girildo** [comment]
Yeah maybe some previous test keeping the domain loaded and not resetting static fields 😀
I'd gladly do that, but I am not sure where to find `GetVideoThumbnailAsync`. Is it supposed to be in the `TextureOps.cs` file?

**Comment by Girildo** [comment]
Ah I guess you're referring to https://github.com/yasirkula/UnityNativeCamera/blob/fd8dcbbac53a54e9f568368f47eaa3b4823854a6/Plugins/NativeCamera/NativeCamera.cs#L493 that indeed seems to have the same issue, but it's a different repository.

**Comment by yasirkula** [comment]
You're right, my mistake :D

**Pull request merged**
